from __future__ import annotations

import importlib
import json
import sys
from pathlib import Path
from typing import Any


def project_root() -> Path:
    """Return the Hyperkey project root (the parent of the ui package)."""
    return Path(__file__).resolve().parent.parent


def ensure_scripts_on_path() -> None:
    """
    Put scripts/ on sys.path without requiring it to be a Python package.

    This is what allows the pipeline modules to keep importing each other
    flatly (`from pipeline import main`, `import app_paths`, ...).
    """
    scripts_dir = project_root() / "scripts"

    if not scripts_dir.exists():
        raise RuntimeError(
            f"Hyperkey scripts directory was not found: {scripts_dir}. "
            "Place the ui folder and hyperkey.py in the project root beside scripts/."
        )

    scripts_text = str(scripts_dir)

    if scripts_text not in sys.path:
        sys.path.insert(0, scripts_text)


def import_app_paths():
    """
    Return the shared scripts/app_paths module.

    The UI needs the same platform-aware paths the pipeline uses, so both
    sides agree on where output goes.
    """
    ensure_scripts_on_path()

    return importlib.import_module("app_paths")


def _import_workflow_module():
    """
    Import scripts/workflow.py without requiring scripts/ to be a Python package.

    Adding scripts/ to sys.path also allows workflow.py to import:
        pipeline.py
        visualise_heatmap.py
        visualise_measurement.py
        outlier_analysis.py
        report.py
    """
    ensure_scripts_on_path()

    return importlib.import_module("workflow")


def _read_generated_summary(result: dict[str, Any]) -> dict[str, Any]:
    """
    Read summary.json generated by pipeline.py.

    Prefer summary_path returned by the backend when available.
    Fall back to output_directory/summary.json for compatibility.
    """
    summary_path = result.get("summary_path")

    if summary_path:
        summary_path = Path(summary_path)
    else:
        output_directory = result.get("output_directory")

        if not output_directory:
            return {}

        summary_path = Path(output_directory) / "summary.json"

    if not summary_path.exists():
        return {}

    try:
        with summary_path.open("r", encoding="utf-8") as handle:
            data = json.load(handle)

        return data if isinstance(data, dict) else {}

    except Exception:
        return {}


def _read_generated_log(result: dict[str, Any]) -> list[str]:
    """
    Read error_log.txt generated by pipeline.py.

    Prefer log_path returned by the backend when available.
    Fall back to output_directory/error_log.txt for compatibility.
    """
    log_path = result.get("log_path")

    if log_path:
        log_path = Path(log_path)
    else:
        output_directory = result.get("output_directory")

        if not output_directory:
            return []

        log_path = Path(output_directory) / "error_log.txt"

    if not log_path.exists():
        return []

    try:
        return log_path.read_text(
            encoding="utf-8",
            errors="replace"
        ).splitlines()

    except Exception:
        return []


def run_hyperkey_backend(
    arguments: list[str],
) -> dict[str, object] | None:
    """
    Run the complete Hyperkey workflow.

    This is the single backend boundary used by the Flet UI.

    Flow:
        Flet UI
            ->
        ui/backend.py
            ->
        scripts/workflow.py
            ->
        scripts/pipeline.py
            ->
        visualise_heatmap.py
            ->
        visualise_measurement.py
            ->
        outlier_analysis.py (optional)
            ->
        report.py
    """
    workflow = _import_workflow_module()

    runner = getattr(workflow, "run_pipeline", None)

    if runner is None:
        raise RuntimeError(
            "scripts/workflow.py does not provide "
            "run_pipeline(cli_arguments=None)."
        )

    result = runner(arguments)

    if result is None:
        return None

    if not isinstance(result, dict):
        return {
            "result": result
        }

    # Keep everything returned directly by workflow.run_pipeline().
    combined: dict[str, object] = dict(result)

    # summary.json is written once during extraction and updated again
    # by workflow.py after all requested processing stages finish.
    summary = _read_generated_summary(result)

    if summary:
        combined.update(summary)

    # Add generated log lines separately for the Flet Logs screen.
    log_lines = _read_generated_log(result)

    if log_lines:
        combined["_logs"] = log_lines

    return combined
